### ISSUE TITLE
Connector failing with NoClassDefFoundError

### ISSUE THREAD

**Issue by sukalpomitra** [fbascheper/kafka-connect-telegram#23]
This is the stack trace that I could found from the connect logs -

[2020-11-10 16:46:36,768] ERROR WorkerSinkTask{id=telegram-sink-v1-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: scala/Product$class (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NoClassDefFoundError: scala/Product$class
	at com.github.fbascheper.kafka.connect.telegram.mapper.StructFieldsExtractor.<init>(StructFieldsValuesExtractor.scala:26)
	at com.github.fbascheper.kafka.connect.telegram.mapper.TelegramMessageMapper.mapAvroStructMessage$1(TelegramMessageMapper.scala:119)
	at com.github.fbascheper.kafka.connect.telegram.mapper.TelegramMessageMapper.map(TelegramMessageMapper.scala:158)
	at com.github.fbascheper.kafka.connect.telegram.TelegramSinkTask$$anonfun$put$1.apply(TelegramSinkTask.scala:57)
	at com.github.fbascheper.kafka.connect.telegram.TelegramSinkTask$$anonfun$put$1.apply(TelegramSinkTask.scala:57)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.github.fbascheper.kafka.connect.telegram.TelegramSinkTask.put(TelegramSinkTask.scala:57)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vbmithr** [comment]
Same here!

Edit: Found the solution, missing scala library in JAR, but still, it would be good if the author would popup and fix adapt things for the state of the world 4y after :)
